# Generated by Django 2.1.2 on 2018-10-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'permissions': (('can_hear', 'Can hear MyModel'),)},
        ),
    ]
